//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnssMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GnssMonitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 数据库操作句柄错误 的本地化字符串。
        /// </summary>
        internal static string DBOperateHandleError {
            get {
                return ResourceManager.GetString("DBOperateHandleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BDS解算 的本地化字符串。
        /// </summary>
        internal static string strBDSProcessMode {
            get {
                return ResourceManager.GetString("strBDSProcessMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先进行配置 的本地化字符串。
        /// </summary>
        internal static string strConfigPromote {
            get {
                return ResourceManager.GetString("strConfigPromote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接数据库{0}失败 的本地化字符串。
        /// </summary>
        internal static string strDatabaseLinkError {
            get {
                return ResourceManager.GetString("strDatabaseLinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据有错误！ 的本地化字符串。
        /// </summary>
        internal static string strDataError {
            get {
                return ResourceManager.GetString("strDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要退出服务器？ 的本地化字符串。
        /// </summary>
        internal static string strExitPromote {
            get {
                return ResourceManager.GetString("strExitPromote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不存在或内容为空，请检查！ 的本地化字符串。
        /// </summary>
        internal static string strFileNotExist {
            get {
                return ResourceManager.GetString("strFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GLONASS解算 的本地化字符串。
        /// </summary>
        internal static string strGlonassProcessMode {
            get {
                return ResourceManager.GetString("strGlonassProcessMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解算软件服务启动失败，可查阅日志了解失败原因！ 的本地化字符串。
        /// </summary>
        internal static string strGnssAnalysisStartFailure {
            get {
                return ResourceManager.GetString("strGnssAnalysisStartFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解算软件服务启动成功 的本地化字符串。
        /// </summary>
        internal static string strGnssAnalysisStartSuccess {
            get {
                return ResourceManager.GetString("strGnssAnalysisStartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPS解算 的本地化字符串。
        /// </summary>
        internal static string strGPSProcessMode {
            get {
                return ResourceManager.GetString("strGPSProcessMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息不全，请提供完整的信息 的本地化字符串。
        /// </summary>
        internal static string strInputIncomplete {
            get {
                return ResourceManager.GetString("strInputIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没找到任何指定记录 的本地化字符串。
        /// </summary>
        internal static string strNoRecord {
            get {
                return ResourceManager.GetString("strNoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择解算模式 的本地化字符串。
        /// </summary>
        internal static string strProcessModeError {
            get {
                return ResourceManager.GetString("strProcessModeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示！ 的本地化字符串。
        /// </summary>
        internal static string strPrompt {
            get {
                return ResourceManager.GetString("strPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录信息不完整 的本地化字符串。
        /// </summary>
        internal static string strRecordUncompleted {
            get {
                return ResourceManager.GetString("strRecordUncompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定站点名已存在 的本地化字符串。
        /// </summary>
        internal static string strStationIsExist {
            get {
                return ResourceManager.GetString("strStationIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知的坐标类型 的本地化字符串。
        /// </summary>
        internal static string strUnknownCoordinate {
            get {
                return ResourceManager.GetString("strUnknownCoordinate", resourceCulture);
            }
        }
    }
}
